export const catalogo = [
  {
    id: '1',
    nome: 'The Batman: Parte II',
    descricao: 'O retorno do Cavaleiro das Trevas em uma nova investigação sombria em Gotham.',
    preco: 'R$ 29,90',
    foto: require('./assets/batman.jpg'),
    avaliacao: '4.9',
    nivelPreco: '$$$',
  },
  {
    id: '2',
    nome: 'Toy Story 5',
    descricao: 'Woody, Buzz e a turma retornam para mais uma aventura emocionante da Pixar.',
    preco: 'R$ 24,90',
    foto: require('./assets/toystory5.jpg'),
    avaliacao: '4.8',
    nivelPreco: '$$',
  },
  {
    id: '3',
    nome: 'Duna: Messias',
    descricao: 'Paul Atreides enfrenta os desafios e conspirações como o imperador do universo.',
    preco: 'R$ 34,90',
    foto: require('./assets/duna.jpg'),
    avaliacao: '4.9',
    nivelPreco: '$$$$',
  },

  {
    id: '4',
    nome: 'Vingadores: A Dinastia Kang',
    descricao: 'Os heróis mais poderosos da Terra se reúnem contra uma grande ameaça multiversal.',
    preco: 'R$ 39,90',
    foto: require('./assets/avengers.jpg'),
    avaliacao: '4.7',
    nivelPreco: '$$$$',
  },
  {
    id: '5',
    nome: 'Super Mario Bros 2',
    descricao: 'Mario e Luigi encaram novos desafios e mundos inéditos no Reino Cogumelo.',
    preco: 'R$ 29,90',
    foto: require('./assets/mario.jpg'),
    avaliacao: '4.7',
    nivelPreco: '$$$',
  },
  {
    id: '6',
    nome: 'Homem-Aranha 4',
    descricao: 'Peter Parker tenta equilibrar sua nova vida anônima com seus deveres de herói.',
    preco: 'R$ 34,90',
    foto: require('./assets/homemaranha.jpg'),
    avaliacao: '4.8',
    nivelPreco: '$$$$',
  },
  {
    id: '7',
    nome: 'Avatar 3: Portador do Fogo',
    descricao: 'Uma jornada imersiva pelos confins de Pandora, apresentando a perigosa tribo do fogo.',
    preco: 'R$ 39,90',
    foto: require('./assets/avatar.jpg'),
    avaliacao: '4.8',
    nivelPreco: '$$$$',
  },
];